version: '3.1'

services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_feed_bot
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  bot:
    build:
      context: .
    restart: on-failure
    environment:
      DATABASE_DSN: ${DATABASE_DSN:-postgres://postgres:postgres@db:5432/news_feed_bot?sslmode=disable}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHANNEL_ID: ${TELEGRAM_CHANNEL_ID}
      FETCH_INTERVAL: ${FETCH_INTERVAL}
      NOTIFICATION_INTERVAL: ${NOTIFICATION_INTERVAL}
      FILTER_KEYWORDS: ${FILTER_KEYWORDS}
      OPENAI_KEY: ${OPENAI_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db: